"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { CalendarPlus, Check, HeartHandshake, Keyboard, Mic, MicOff, Volume2 } from "lucide-react";
import { loadProfile, loadTasks, saveTasks } from "@/lib/storage";
import type { GardenProfile, GardenTask } from "@/lib/types";

interface SpeechRecognitionEventLike {results:ArrayLike<{0:{transcript:string}}>}
interface RecognitionLike {lang:string;interimResults:boolean;continuous:boolean;start:()=>void;stop:()=>void;onresult:((e:SpeechRecognitionEventLike)=>void)|null;onerror:(()=>void)|null;onend:(()=>void)|null;}
type RecognitionConstructor=new()=>RecognitionLike;

export function CareDashboard(){
  const [profile,setProfile]=useState<GardenProfile|null>(null);const [tasks,setTasks]=useState<GardenTask[]>([]);const [query,setQuery]=useState("");const [reply,setReply]=useState("");const [listening,setListening]=useState(false);const [voiceSupported,setVoiceSupported]=useState(true);
  useEffect(()=>{setProfile(loadProfile());setTasks(loadTasks());const w=window as typeof window&{SpeechRecognition?:RecognitionConstructor;webkitSpeechRecognition?:RecognitionConstructor};setVoiceSupported(!!(w.SpeechRecognition||w.webkitSpeechRecognition));},[]);
  const top=tasks.find(t=>!t.done)||tasks[0];
  function speak(text:string){if(!("speechSynthesis" in window)){setReply("当前浏览器不支持朗读，可以直接看屏幕上的大字。");return;}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang="zh-CN";utterance.rate=.88;window.speechSynthesis.speak(utterance);}
  function startListening(){const w=window as typeof window&{SpeechRecognition?:RecognitionConstructor;webkitSpeechRecognition?:RecognitionConstructor};const Ctor=w.SpeechRecognition||w.webkitSpeechRecognition;if(!Ctor){setVoiceSupported(false);setReply("当前浏览器不支持语音输入，请在下方打字。");return;}const recognition=new Ctor();recognition.lang="zh-CN";recognition.interimResults=false;recognition.continuous=false;recognition.onresult=e=>{const text=e.results[0]?.[0]?.transcript||"";setQuery(text);answer(text);};recognition.onerror=()=>{setListening(false);setReply("这次没有听清，请再说一次，或者直接打字。");};recognition.onend=()=>setListening(false);setListening(true);recognition.start();}
  function answer(text=query){const content=text.trim();if(!content)return;let next=top?`今天先做：${top.title}。${top.detail}${top.avoid?` 暂时不要：${top.avoid}。`:""}`:"还没有今日任务，请先到标准版建立菜园并生成任务。";if(/完成|做完/.test(content)&&top){markDone();next=`好的，已经记下“${top.title}”完成了。`; }else if(/为什么|原因/.test(content)&&top)next=`因为${top.reason}。`;else if(/家人|孩子|代管/.test(content))next="可以打开家人代管演示，让家人协助查看任务和记录。";setReply(next);}
  function markDone(){if(!top)return;const next=tasks.map(t=>t.id===top.id?{...t,done:true}:t);setTasks(next);saveTasks(next);}
  function exportOne(){if(!top)return;const date=new Date().toISOString().slice(0,10).replaceAll("-","");const ics=["BEGIN:VCALENDAR","VERSION:2.0","BEGIN:VEVENT",`UID:${top.id}@garden-guardian`,`DTSTART:${date}T080000`,`DTEND:${date}T083000`,`SUMMARY:${top.cropName}：${top.title}`,`DESCRIPTION:${top.detail}`,"END:VEVENT","END:VCALENDAR"].join("\r\n");const url=URL.createObjectURL(new Blob([ics],{type:"text/calendar;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="今天的菜园提醒.ics";a.click();URL.revokeObjectURL(url);}
  if(!profile)return <div className="rounded-[2.5rem] border-2 border-leaf-200 bg-white p-8 text-center shadow-soft"><h2 className="text-3xl font-bold text-leaf-900">先告诉管家你种了什么</h2><p className="mt-4 text-xl leading-9 text-leaf-800">建立一次菜园档案，之后关怀版会自动显示最重要的任务。</p><Link href="/app" className="btn-primary mt-7 !min-h-14 !text-lg">去建立菜园</Link></div>;
  return <div className="grid gap-6 lg:grid-cols-[1.35fr_.65fr]">
    <section className="rounded-[2.5rem] border-2 border-leaf-200 bg-white p-7 shadow-soft md:p-10"><span className="inline-flex rounded-full bg-amber-100 px-4 py-2 font-bold text-amber-900">{top?.priority==="urgent"?"优先处理":"今天要做"}</span>{top?<><p className="mt-6 text-xl font-bold text-leaf-700">{top.cropName}</p><h2 className="mt-2 text-4xl font-bold leading-tight text-leaf-900 md:text-6xl">{top.title}</h2><p className="mt-6 text-xl leading-10 text-leaf-800">{top.detail}</p>{top.avoid&&<div className="mt-5 rounded-2xl bg-amber-50 p-4 text-lg font-bold text-amber-950">先别做：{top.avoid}</div>}<div className="mt-8 flex flex-wrap gap-3"><button className="btn-primary !min-h-14 !text-lg" onClick={()=>speak(`${top.title}。${top.detail}${top.avoid?`暂时不要${top.avoid}`:""}`)}><Volume2/>读给我听</button><button className="btn-secondary !min-h-14 !text-lg" onClick={exportOne}><CalendarPlus/>提醒我</button><button className="btn-secondary !min-h-14 !text-lg" onClick={markDone}><Check/>我做完了</button></div></>:<><h2 className="mt-7 text-4xl font-bold text-leaf-900">今天还没有任务</h2><p className="mt-5 text-xl leading-9">请到标准版生成一次今日任务。</p><Link href="/app" className="btn-primary mt-7 !min-h-14 !text-lg">去生成任务</Link></>}</section>
    <div className="space-y-5"><section className="rounded-[2.5rem] bg-leaf-700 p-7 text-white shadow-soft"><button onClick={startListening} className="grid min-h-48 w-full place-items-center text-center" aria-label={listening?"正在听，请说话":"开始语音提问"}><span>{listening?<MicOff className="mx-auto animate-pulse" size={54}/>:<Mic className="mx-auto" size={54}/>}<strong className="mt-4 block text-2xl">{listening?"正在听…":"点一下，说问题"}</strong><span className="mt-2 block text-leaf-100">{voiceSupported?"例如：今天要做什么？":"当前浏览器请用文字输入"}</span></span></button></section>
      <section className="rounded-[2rem] border border-leaf-200 bg-white p-5"><div className="flex items-center gap-2 font-bold text-leaf-900"><Keyboard/>也可以打字</div><textarea value={query} onChange={e=>setQuery(e.target.value)} className="field mt-4 min-h-24 py-3 text-lg" placeholder="今天要做什么？"/><button className="btn-primary mt-3 w-full !min-h-14 !text-lg" onClick={()=>answer()}>问菜园管家</button>{reply&&<div className="mt-4 rounded-2xl bg-leaf-50 p-4 text-lg leading-8"><p>{reply}</p><button onClick={()=>speak(reply)} className="mt-3 inline-flex items-center gap-2 font-bold text-leaf-700"><Volume2/>朗读回答</button></div>}</section>
      <Link href="/family-demo" className="flex min-h-16 items-center justify-center gap-3 rounded-2xl border-2 border-leaf-200 bg-white font-bold text-leaf-800"><HeartHandshake/>让家人帮忙照看</Link>
    </div>
  </div>;
}
